#!/bin/sh

faces="Auvaiyar Vaigai ThiruValluvar"
for face in $faces
do
    ufo=source/${face}-Regular.ufo
    psfsetkeys -k "copyright" --filepart OFL.txt $ufo
    psfsetkeys -k "openTypeNameLicense" --file OFL.txt $ufo
    psfsetversion $ufo 0.500
    psfsetglyphorder -i source/glyph_data-${face}.csv $ufo
    psfsetpsnames -i source/glyph_data-${face}.csv $ufo
    psfsyncmasters source/${face}Roman.designspace source/${face}Italic.designspace
    psfmakewoffmetadata -n ${face} -i in.nlci.fonts $ufo
done

for ufo in source/*.ufo
do
    psfnormalize -v 3 -p checkfix=fix $ufo &
done
wait

location=documentation
filepath=${location}/${face}-features
odt=${filepath}.odt
pdf=${filepath}.pdf
if [ $odt -nt $pdf ]
then
    soffice --convert-to pdf --outdir $location $odt
fi

for auto in tools/auto-*
do
    ./$auto tests/$(basename $auto .py).txt
done
