#!/bin/sh

psfglyphs2ufo source/ThiruValluvarRoman.glyphs source
psfglyphs2ufo source/ThiruValluvarItalic.glyphs source
	
#psfglyphs2ufo source/AuvaiyarItalic.glyphs source
#psfglyphs2ufo source/AuvaiyarRoman.glyphs source

#psfglyphs2ufo source/VaigaiRoman.glyphs source
#psfglyphs2ufo source/VaigaiItalic.glyphs source

./preflight
