#!/bin/sh

faces="ThiruValluvar Auvaiyar Vaigai"
for face in $faces
do
    ufo=source/${face}-Regular.ufo
    psfsetkeys -k "copyright" --filepart OFL.txt $ufo
    psfsetkeys -k "openTypeNameLicense" --file OFL.txt $ufo
    psfsetversion $ufo 0.303
    psfsyncmasters source/${face}Roman.designspace source/${face}Italic.designspace
    psfmakewoffmetadata -n ${face} -i in.nlci.fonts $ufo
done

cd source
for ufo in *.ufo
do
    psfnormalize -v 3 -p checkfix=fix $ufo
done
cd ..
