#!/bin/sh

faces="ThiruValluvar Auvaiyar Vaigai"
cd source
mkdir logs
for ufo in *.ufo
do
    psfsetkeys -p backup=0 -k "copyright" --filepart ../OFL.txt $ufo
    psfsetkeys -p backup=0 -k "openTypeNameLicense" --file ../OFL.txt $ufo
    psfsetversion $ufo 0.303
    psfnormalize -v 3 -p checkfix=fix $ufo
done
cd ..
for face in $faces
do
    psfmakewoffmetadata -n ${face} -i in.nlci.fonts source/${face}-Regular.ufo -l source/logs/${face}_woff.log
done
