#!/bin/bash

extra=$PWD
directory=$(basename $extra)
project=../${directory%%_local}
ufo=${project}/results/ufo
wscript=${project}/wscript
# grep -E "faces|styles" $wscript | grep = > wscript.py
rm -f *.sfd

pushd ${project}
smith distclean -l
smith configure -l
smith build -l
popd

pushd ${ufo}
for ttf in *.ttf
do
    echo $ttf
    fontforge -script ${extra}/ttf2sfd.ff $ttf
done
for sfd in Auvaiyar*.sfd Vaigai*.sfd
do
    echo $sfd
    fontforge -script ${extra}/emsize.ff $sfd
done
popd

sort -o cs/charis/pre.txt cs/charis/composite.txt cs/charis/decomposition.txt
sort -o cs/gentium/pre.txt cs/gentium/composite.txt cs/gentium/decomposition.txt
python addchars.py ${project}/results/ufo

pushd ${ufo}
for sfd in *.sfd
do
    echo $sfd
    pwd
    python ../../tools/ffaddapstotaml $sfd ${extra}/tmp.sfd
    python ../../tools/ffaddvaptotaml ${extra}/tmp.sfd $sfd
    rm ${extra}/tmp.sfd
done
popd

mv -v ${ufo}/*.sfd ${project}/source
