#!/bin/bash

faces=(ThiruValluvar Auvaiyar Vaigai)
styles=(Regular Bold Italic "Bold Italic")
desc_long="Tamil script font for all languages using the Tamil script"

export nlci=$HOME/script/tools
export src=source
# source ${nlci}/prepare.bash

# pushd ${src}
# for sfd in *-???*.sfd
# do
#     echo $sfd
#     rm -f tmp.sfd
#     python ../tools/ffaddapstotaml $sfd tmp.sfd
#     python ../tools/ffaddvaptotaml tmp.sfd $sfd
#     rm -f tmp.sfd
# done
# popd

cat cs/main_import.txt tools/latin.txt > cs/latn_import.txt
cat                    tools/runic.txt > cs/runr_import.txt
source ${nlci}/metadata.bash

pushd ${src}
for sfd in *-???*.sfd
do
    mv -v ${sfd}.BAK-C ${sfd}
done
popd

for ufo in ${src}/*.ufo
do
    ./tools/anchors.py $ufo
done

# rm -f ${src}/*-???*.sfd*
pushd ${src}
for fi in ${!faces[@]} # loop over indices
do
    f=${faces[$fi]} # fi is the index into the array faces
    ${nlci}/ufo2glyphdata.py --langs languages.csv --feats features.csv $HOME/pub/doc/Adobe/agl-aglfn/aglfn.txt ${f}-Regular.ufo glyph_data-${f}.csv
done
popd
./preflight
echo "done producing UFO sources"
