#!/bin/bash

faces=(ThiruValluvar Auvaiyar Vaigai)
styles=(Regular Bold Italic "Bold Italic")
desc_long="Pan Tamil font designed to support all the languages using the Tamil script."

export nlci=$HOME/script/tools
export src=source
# source ${nlci}/prepare.bash

# pushd ${src}
# for sfd in *-???*.sfd
# do
#     echo $sfd
#     rm -f tmp.sfd
#     python ../tools/ffaddapstotaml $sfd tmp.sfd
#     python ../tools/ffaddvaptotaml tmp.sfd $sfd
#     rm -f tmp.sfd
# done
# popd

cat cs/main_import.txt tools/latin.txt > cs/latn_import.txt
cat                    tools/runic.txt > cs/runr_import.txt
source ${nlci}/metadata.bash

pushd ${src}
for sfd in *-???*.sfd
do
    mv -v ${sfd}.BAK-C ${sfd}
done
popd

for ufo in ${src}/*.ufo
do
    ./tools/anchors.py $ufo
done

# rm -f ${src}/*-???*.sfd*
echo "done producing UFO sources"
